name: publish to npmjs

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20' # Stick to LTS to avoid the 'engine' warning
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - run: pnpm i --frozen-lockfile

      # This step bridge the OIDC token to pnpm's environment
      - name: Publish to npm
        run: pnpm publish --no-git-checks --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # When using OIDC/Trusted Publishing, this token is automatically swapped for an npm one